-- Barangay San Jose Automated Blotter System
-- Schema + seed data

CREATE DATABASE IF NOT EXISTS barangay_blotter_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE barangay_blotter_db;

-- Users / RBAC
DROP TABLE IF EXISTS system_logs;
DROP TABLE IF EXISTS case_resolutions;
DROP TABLE IF EXISTS blotter_records;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('captain','secretary','councilor','lupon') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Main blotter records
CREATE TABLE blotter_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reference_number VARCHAR(30) NOT NULL UNIQUE,
  complainant_name VARCHAR(120) NOT NULL,
  respondent_name VARCHAR(120) NOT NULL,
  incident_type VARCHAR(80) NOT NULL,
  incident_date DATE NOT NULL,
  incident_time TIME NOT NULL,
  location VARCHAR(120) NOT NULL,
  narrative TEXT NOT NULL,
  case_status ENUM('Open','Under Mediation','Resolved','Closed') NOT NULL DEFAULT 'Open',
  created_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,

  CONSTRAINT fk_blotter_created_by
    FOREIGN KEY (created_by) REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Case resolutions
CREATE TABLE case_resolutions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  blotter_record_id INT NOT NULL,
  resolution_type VARCHAR(80) NOT NULL,
  settlement_details TEXT NOT NULL,
  resolved_by INT NULL,
  resolved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_resolution_blotter
    FOREIGN KEY (blotter_record_id) REFERENCES blotter_records(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_resolution_resolved_by
    FOREIGN KEY (resolved_by) REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- System logs
CREATE TABLE system_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  action VARCHAR(50) NOT NULL,
  target_table VARCHAR(60) NOT NULL,
  target_id INT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  INDEX idx_system_logs_user_id (user_id),
  INDEX idx_system_logs_target (target_table, target_id),
  CONSTRAINT fk_logs_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Helpful indexes for search
CREATE INDEX idx_blotter_incident_date ON blotter_records(incident_date);
CREATE INDEX idx_blotter_incident_type ON blotter_records(incident_type);
CREATE INDEX idx_blotter_complainant_name ON blotter_records(complainant_name);
CREATE INDEX idx_blotter_respondent_name ON blotter_records(respondent_name);
CREATE INDEX idx_blotter_case_status ON blotter_records(case_status);
CREATE INDEX idx_blotter_location ON blotter_records(location);

-- Seed data
-- Note: bcrypt hashes must be generated by the PHP app. For convenience in initial setup,
-- we insert placeholder hashes here. After first run, create users via the app.
-- To avoid auth issues, these seed user hashes are left empty intentionally.
-- Replace with real hashes after creating users.

INSERT INTO users (full_name, username, password_hash, role)
VALUES
('Barangay Captain', 'captain', '$2y$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'captain'),
('Barangay Secretary', 'secretary', '$2y$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'secretary'),
('Barangay Councilor', 'councilor', '$2y$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'councilor'),
('Lupon Member', 'lupon', '$2y$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'lupon');

-- Helper comment for reference numbers: BSJ-YYYYMM-0001

INSERT INTO blotter_records
(reference_number, complainant_name, respondent_name, incident_type, incident_date, incident_time, location, narrative, case_status, created_by)
VALUES
('BSJ-202401-0001','Maria Santos','Juan Dela Cruz','Neighborhood Dispute','2024-01-05','14:20:00','Sitio Mabuhay','Verbal altercation during community gathering.', 'Open', 2),
('BSJ-202401-0002','Ramon Villanueva','Pedro Reyes','Threat/Harassment','2024-01-12','09:10:00','Barangay Hall Area','Complainant reports ongoing threats via messages.', 'Under Mediation', 1),
('BSJ-202402-0003','Elena Cruz','Sergio Mendoza','Noise Disturbance','2024-02-03','21:45:00','Zone 1','Excessive loud music past curfew.', 'Resolved', 2),
('BSJ-202402-0004','Ana Garcia','Luis Santos','Property Damage','2024-02-18','17:30:00','Zone 3','Fence damaged during misunderstanding.', 'Closed', 2),
('BSJ-202403-0005','Josefa Perez','Marvin Lopez','Minor Physical Injury','2024-03-01','11:05:00','Sitio Riverside','Minor altercation resulting in injury.', 'Open', 3),
('BSJ-202403-0006','Carlos Ramos','Edith Navarro','Family Dispute','2024-03-10','16:20:00','Zone 2','Domestic issue; complainant seeks mediation.', 'Under Mediation', 1),
('BSJ-20E2404-0007','Norma Chavez','Gerald Bautista','Theft Allegation','2024-04-07','08:55:00','Zone 4','Missing items reported after house event.', 'Open', 2),
('BSJ-202404-0008','Miguel Flores','Rafael Santiago','Verbal Abuse','2024-04-20','19:05:00','Sitio Mabuhay','Insults exchanged at basketball court.', 'Resolved', 1),
('BSJ-202405-0009','Theresa Lim','William Cruz','Land Boundary Issue','2024-05-02','13:15:00','Zone 5','Land boundary dispute between families.', 'Under Mediation', 2),
('BSJ-202405-0010','Olivia Mercado','Dante Torres','Trespassing','2024-05-14','10:25:00','Zone 3','Respondent entered property without consent.', 'Open', 4),
('BSJ-202406-0011','Victor Hernandez','Ramon Villanueva','Neighborhood Dispute','2024-06-03','15:40:00','Barangay Hall Area','Repeated arguments over parking space.', 'Resolved', 2),
('BSJ-202406-0012','Patricia Mendoza','Jose Santos','Threat/Harassment','2024-06-11','20:10:00','Sitio Riverside','Threatening messages received.', 'Under Mediation', 1),
('BSJ-202406-0013','Arthur Reyes','Catherine Lopez','Noise Disturbance','2024-06-21','22:30:00','Zone 1','Loud noise during late hours.', 'Closed', 3),
('BSJ-202407-0014','Diana Santos','Rico Bautista','Property Damage','2024-07-06','18:20:00','Zone 2','Car key scratched by unknown person; suspect respondent.', 'Open', 2),
('BSJ-202407-0015','Samuel Navarro','Maria Perez','Theft Allegation','2024-07-15','09:30:00','Zone 4','Alleged theft during sari-sari store event.', 'Under Mediation', 4),
('BSJ-202408-0016','Grace Villanueva','Henry Chavez','Family Dispute','2024-08-01','12:10:00','Zone 5','Family disagreement; request for reconciliation.', 'Resolved', 1),
('BSJ-202408-0017','Rolando Torres','Edith Navarro','Minor Physical Injury','2024-08-09','14:50:00','Sitio Mabuhay','Scuffle at school gate; minor injury.', 'Closed', 2),
('BSJ-202409-0018','Lourdes Cruz','Juan Dela Cruz','Verbal Abuse','2024-09-04','08:40:00','Zone 3','Arguments and disrespectful language.', 'Open', 3),
('BSJ-202410-0019','Hector Santiago','Ana Garcia','Trespassing','2024-10-10','16:05:00','Zone 1','Entered yard without permission.', 'Under Mediation', 2),
('BSJ-202410-0020','Marian Chavez','Gerald Bautista','Land Boundary Issue','2024-10-25','11:25:00','Sitio Riverside','Boundary markers removed; needs verification.', 'Resolved', 1);

-- Seed some resolutions for a subset
-- resolution_type values are free-form but should match expected strings in UI.

INSERT INTO case_resolutions
(blotter_record_id, resolution_type, settlement_details, resolved_by, resolved_at)
VALUES
(3,'Barangay Mediation','Both parties agreed to maintain quiet hours and avoid loud music.','2','2024-02-10 10:00:00'),
(4,'Settlement Agreement','Respondent repaired the damaged fence within 7 days with assistance from barangay workers.','2','2024-02-28 15:00:00'),
(8,'Conciliation','Respondent apologized in front of witnesses and will refrain from harassment.','1','2024-04-25 09:30:00'),
(11,'Reconciliation Meeting','Parking space rules were clarified; complainant and respondent agreed to a schedule.','2','2024-06-10 14:00:00'),
(16,'Reconciliation','Family members agreed on a communication plan and counseling schedule.','1','2024-08-05 11:00:00');

